apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: zad2gitops 
              image: weronika00/hefalump-cron:latest
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/weronika0/config_repo.git /tmp/config_repo && kubectl apply -f /tmp/config_repo/deployment.yaml && kubectl apply -f /tmp/config_repo/service.yaml && kubectl apply -f /tmp/config_repo/ingress.yaml